micheleg/dash-to-dock

theming.js

This is the modified patch started by @franglais125 to fix the border opacity issue #314.

Customize border opacity following the dash background value

---

po/zh_CN.po

Update Simplified Chinese translation.

---

Makefile

Make INSTALLBASE a bit more flexible, remove trailing whitespace

---

po/es.po

Updated file with `make potfile`

Update Spanish translation.

---

po/es.po
po/pt.po
po/pt_BR.po

This adds translations for the feature added in commit 45edb280170969ca9cda7f3eee2fcb5e8ae7560e and removes obsolete strings.

Update Spanish and Portuguese translations

---

po/de.po

Add missing translation for de.

add missing translation

---

appIcons.js
dash.js
docking.js
intellihide.js
prefs.js
theming.js
windowPreview.js

Fixed warnings and errors accessing to dead objects as per upstream changes.
This meant to be added to #975, but I had no time to push in time :(

Various cleanups and warning fixes

---

po/zh_TW.po

Update Tradition Chinese

---

prefs.js

it should not be "Cutomize  opacity" but "Customize opacity".

fixed a typo in a translatable string.

---

po/zh_TW.po

Correct one translation in Traditional Chinese.

---

po/tr.po

This patch improves Turkish translation using GNOME Shell's Turkish translation.

Improve Turkish translation

---

docking.js

Since GNOME 3.34, the overview is disabled in GNOME Classic. Handle
that case so that the extension is still usable in that environment.

docking: Handle no-overview case

---

download.md

Fixed typo in download.md

---

po/es.po

Updated ES translation: show straight corners + show mounted devices + show trash icon

---

appIconIndicators.js
appIcons.js
dash.js
docking.js
fileManager1API.js
launcherAPI.js
metadata.json
stylesheet.css
theming.js
utils.js
windowPreview.js

Add code to make the extension to work on gnome-3.36 as per the upstream changes.
Again, keeping compatibility with 3.34, while technically possible, makes things way harder to maintain.

Gnome 3.36 support

---

po/eu.po

Added Basque localization.

---

po/zh_TW.po

i18n: zh_TW: update and improve translation

---

Makefile
appIcons.js
dash.js
dbusmenuUtils.js
docking.js
launcherAPI.js

Cleanup a bit the changes introduced in #1245, as per the comment to @rhendric, and particularly:
- Make importing DBusmenu dynamic (may not be available in other distros than ubuntu)
- Change the animation mechanism (doesn't work in 3.38, but mostly could be simplified).

Unity features improvements

---

docking.js
metadata.json

Quick fix #1359 causing application screen flickering.

Quick Fix #1359

---

docking.js

Do not animate disposed icons

---

theming.js

Fixes https://github.com/micheleg/dash-to-dock/issues/1553

Fix inverted green/blue colors in background

---

default.nix

This allows installation on NixOS with:
nix-shell
make
make install
Signed-off-by: Rafael Kitover <rkitover@gmail.com>

Add default.nix for NixOS users.

---

README.md

this would be instead of https://github.com/micheleg/dash-to-dock/pull/1627

change README to document actual behavier

---

.eslintrc.yml
.github/workflows/make.yml
Makefile
appIcons.js
dash.js
docking.js
fileManager1API.js
locations.js
po/es.po
utils.js
windowPreview.js

Fixes https://github.com/micheleg/dash-to-dock/issues/1654

Simple make CI

---

locations.js

Because `g_file_monitor_set_rate_limit` doesn't work. It's a stub in
glib!
Fixes: https://launchpad.net/bugs/1962699

locations: Reintroduce manual rate limiting for trash monitoring

---

po/es.po

Added some missing locations translations

Add locations translations to es.po

---

Settings.ui
_stylesheet.scss
appIconIndicators.js
appIcons.js
dash.js
docking.js
intellihide.js
locations.js
prefs.js
schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml
theming.js
utils.js
windowPreview.js

Lots of fixes addressing mostly usage with GNOME 41, see each commits for further details.

GNOME 41 round of fixes

---

Settings.ui
appIconIndicators.js
appIcons.js
docking.js
schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml

Because of https://github.com/pop-os/cosmic-dock/issues/139, thank you for the reminder!

Pop os changes

---

po/es.po

Added some missing strings to spanish translations

Update spanish (Spain) translation

---

appIcons.js
dash.js
docking.js
fileManager1API.js
locations.js
theming.js
utils.js

Use JS Symbol's to manage connection labels.

Symbol labels

---

docking.js

Ensure that the animation duration is computed according to the St
Settings values, taking in account both the slowdown factor and the
animation disablement.
Closes: #1798

docking: Respect St.Settings for animation duration

---

.gitignore
Settings.ui
prefs.js

Move shrink to apperance and remove scrolled windows in recent shell versions.

Settings cleanups

---

appIcons.js

appIcons: Monitor windows workspace changes when isolating workspaces

---

.gitignore
Settings.ui
_stylesheet.scss
appIcons.js
dash.js
docking.js
theming.js

Use more generated code to avoid having to repeat the same logic multiple times.
Previous work was in #1826

Stylesheet css generation cleanups

---

docking.js
intellihide.js
metadata.json
utils.js
windowPreview.js

Add GNOME 44 support

---

README.md

docs: add dependency for gettext to build section

---

.eslintrc.yml
appIconIndicators.js
appIcons.js
appSpread.js
dash.js
dbusmenuUtils.js
desktopIconsIntegration.js
docking.js
extension.js
fileManager1API.js
intellihide.js
launcherAPI.js
lint/eslintrc-gjs.yml
lint/eslintrc-shell.yml
locations.js
prefs.js
theming.js
utils.js
windowPreview.js

These rules are meant to have better code quality, maintainability and to avoid errors.
So let's use the same that upstream gnome-shell and gjs are using.

Code cleanup using stricter ESLint rules as per GNOME shell upstream

---

appSpread.js
locations.js

Handle the case in which the shell could hang when working with locations as per https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/+bug/1997264

Locations hanging fixes

---

locations.js
metadata.json

As per e.g.o review, and also release new version.

locations: Keep track of launch wait timeouts

---

locations.js

fix: this._launchMaxWaitIds is undefined

---

docking.js

That's used in theming
Related-to: #1949

docking: export Docking.State enum

---

appIconIndicators.js
dash.js
utils.js

utils: Use St.IconTheme if available

---

Settings.ui
appIcons.js
docking.js
prefs.js
schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml

“Wiggle” conveys the meaning better than “Dance” for the urgent icon animation.

Change "dance" to "wiggle"

---

dash.js

Reverted 2 lines causing the regression.

Fixed the lack of app display on Gnome 41/42 

---

.eslintrc.yml
appIconIndicators.js
appIcons.js
appSpread.js
dash.js
dbusmenuUtils.js
dependencies/gi.js
docking.js
intellihide.js
locations.js
notificationsMonitor.js
prefs.js
theming.js
utils.js
windowPreview.js

Use dangle comma for imports and shorter syntax.

Imports cleanups

---

locations.js
locationsWorker.js

Some fixes to handle issues due to the ESM port.

Locations 45 fixes

---

po/sl-po

Created sl.po with Slovenian translation

Created sl-po

---

po/es.po

Update Spanish translations

---

po/uk_UA.po

Use plural forms in the translation (sync with PR #2102 )

Update Ukrainian translation (sync with PR #2102)

---

_stylesheet.scss

Fix https://github.com/micheleg/dash-to-dock/issues/2160

Fix dot height in default mode

---

_stylesheet.scss
appIcons.js

Make possible to theme updating icons and avoid actions to be available during that phase.

Icons: update state cleanups

---

dependencies/gi.js
theming.js

Closes: https://github.com/micheleg/dash-to-dock/issues/2284

theming: Add support for Cogl.Color since Clutter.Color is deprecated in 47

---

dash.js

Three scrolling fixes, including LP#2102002 and #2301 
See the individual commits for details.

Scrolling fixes
