micheleg/dash-to-dock

Makefile, Settings.ui, appIconIndicators.js, appIcons.js, dash.js, docking.js, fileManager1API.js, locations.js, prefs.js, schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml
This set of changes adds Trash and Removable Device/Drive icons similar to what the Unity dock offers. 
I don't consider it a complete change at this point; I think the code organisation isn't correct, if nothing else, but I'm particularly interested in feedback on the way I created the icons using DesktopAppInfo.
Other obvious shortcomings:
- Lack of Translations
- Nautilus dependency in Empty Trash call
- No drag-and-drop for Trash (I don't personally care about this)
- 'Inauthentic' placement of Trash Icon
=> RFC: Trash and Removable Device Icons

extension.js
Make sure we disconnect from the 'extension-state-changed' signal in the disable
function even if dockManager failed to destroy properly. If we fail to
disconnect from that signal, conditionallyenabledock will be called when the
next extension is disabled, and ubuntu-dock will re-enable itself.
=>  extension: Ensure signal disconnection 

docking.js
this.dash has a longer life-time that this._box so we need to manually
disconnect the signal connection to avoid invalid access to already destroyed
variables.
Fixes: #839
=> docking: Fix leaking signal connection 

appIconIndicators.js
This signals theme writers they have full control of the indicator
style, as we do not touch them.
=> Add a .default class to the appiconindicators.

theming.js
Populate _trackedWindows using global.window_group.get_children() instead of
global.get_window_actors() to guarantee a window is removed from the
_trackedWindows map when the global.window_group 'actor-removed' signal is
received. Without this guarantee we might keep a reference to a destoyed window
actor, causing troubles when trying to disable the extension.
Fixes: https://github.com/micheleg/dash-to-dock/issues/641
=> theming: Ensure _trackingWindows contains valid windows

debian/changelog, debian/control
The previous version got into disco release before the gnome-shell that it needed. i.e. it broke the version of shell that people were using. We can add some dependencies to make sure this doesn't happen, and re-upload.
I'm uploading this to disco now. Please could you also pull the ubuntu-dock-64ubuntu4 tag from my fork?
/cc @3v1n0
=> Ubuntu depends working version

utils.js
Since we're in a class there should be no final comma, and the function can be
marked as static
=> utils: use ES6 syntax to define _decimalToHex method

Settings.ui, appIcons.js, schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml
When clicking over an icon the last used application window will be focused; in
case the application is already the focused one, then we open the previews.
This allows to reduce the clicks when using multiple application icons to go
back and forth windows.
=> appIcons: Add Focus or Previews click action

po/pl.po
The Polish translation has a Windows line ending which causes problems for at least Launchpad's importer.
I believe this issue was caused by the gtranslator app. The app has gotten updates recently so hopefully that bug was fixed.
=> Fix Polish translation header

Settings.ui, prefs.js, schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml, theming.js
The panel dynamic transparency was dropped upstream:
https://gitlab.gnome.org/GNOME/gnome-shell/commit/9cfb51c106abd1f96012bf39f3d329cf060035cf
so this option does not make sense any more.
@3v1n0 @azzar1 : any objection? Is this something you are planning to keep supporting in Ubuntu? I'm even considering dropping the 'Dynamic' mode all together.
=> Remove the Adaptive transparency mode.

theming.js
Redefine isNear so that we can pass it to the signal (that seems
to be used by other extensions)
=> theming: fix missing variable definition as per previous commit

windowPreview.js
As per upstream commit 4d2dce2c, the actual close button is generated using
custom css and a symbolic icon.
Apply the same change to dash-to-dock too, or the window preview close button
will miss the 'x'.
=> windowPreview: Use symbolic icon for close button

stylesheet.css, theming.js
In stylesheet.css, the border radius is set to 9px for the shrinked and the built-in theme for dash, in order to reduce its size. 
Since the default shell theme is [already using 9px border-radius for dash](https://gitlab.gnome.org/GNOME/gnome-shell/blob/348d3037941b9d43f30cf16b7ba396acdef8426f/data/theme/gnome-shell-sass/_common.scss#L1311), this doesn't really change anything. Additionally, when using custom user-theme for gnome-shell, the border-radius defined in dash-to-dock's stylesheet.css overrides any user-themed stylesheets, possibly breaking the appearence of the shrinked dash with custom gnome-shell themes.
This PR makes dash-to-dock use same border-radius for shrinked and non-shrinked dash, to prevent issues with user-themes.
Here's an example of the issue using the Arc shell …
=> Don't reset border-radius for shrinked dash

Settings.ui, prefs.js
We were relying on the settings enum matching the combobox index. Since we
dropped the adaptive transparency mode, we need to explicitely map the combobox
entries via their id and refer to it when getting/setting the option.
Regression introduced by: 8ccc7d2d55e1b425be605ff3d29052f5a43994ec
Fix #926.
=> Fix regression with transparencey settings UI.

appIconIndicators.js, appIcons.js, dash.js, docking.js, extension.js, intellihide.js, metadata.json, theming.js, utils.js, windowPreview.js
Another breaking update upstream that needs some changes for which it might be quite hard to maintain multiple versions (while could be possible for some classes, https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/559 will make it even more impossible).
So, better to do all at once:
- Inheriting from native Actors instead of composition
- Cleanup settings object usage, by avoiding passing it eveywhere
- Remove Tweener to animate, in favor of new Clutter transitions (see [upstream change](https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/669))
=> Support GNOME 3.34 and modernize code

locations.js
I missed this originally.
This is the one outstanding change from #677 that isn't merged.
=> locations: Fix a remaining use of `nautilus` vs `gio open`

appIcons.js
Starting from GNOME/gnome-shell upstream commit ff3d32dd18 AppDisplay is
meant to be used only by the AppGrid and in fact it supports DnD drop
operations, being a drop target for other icons in order to be able to
create an app folder.
However dash-to-dock doesn't need anything of that, so in order to have
proper dock dnd inherit the app icons from the newly introduced (available
since the commit above, included in 3.34.0) Dash.DashIcon
LP: #1846477, #1847102
=> MyAppIcon: Inherit from Dash.DashIcon

docking.js
When using the wheel over the dash to change from a workspace to another, a warning is shown in the log because it is still using .actor to access a widget. This patch fixes it.
=> docking.js: fix warning when using wheel

appIconIndicators.js
The intended function name is probably `destroy` and not `destory`.
=> Fixed a typo

locations.js
I forgot to add this originally. Without it, we don't know that
the icon is a location rather than an app, and some undesired items
are added to the menu.
Mount icons already had this set and didn't have a problem.
Fixes #1037
=> locations: Fix missing behaviour for volume backed locations

stylesheet.css
The built-in theme does not account for Dash to Dock being able to place the dock anywhere on the screen, causing mismatched rounded corners if the dock is not placed on the left hand side while the built-in theme is enabled.
Fixes https://github.com/micheleg/dash-to-dock/issues/1010
=> Fix border radius for built-in theme

docking.js
In this PR, support has been added to the [workspace grid](https://github.com/zakkak/workspace-grid) extension, in case the user has installed it. Previously, swapping the workspaces using the scroll over the dock was causing unexpected behavior when using the Dash to Dock in conjunction with the Workspaces Grid (jumping workspaces 2 in 2, 3 in 3, and so on) making it very annoying to use both extensions together.
To add support, functions exported by the Workspaces Grid extension were used.
=> Add support to workspace-grid extension

appIcons.js
The AppIconMenu was only updated when show-window-preview option was enabled, which led to the "Quit" menu entry being displayed on non-running applications, and the number of windows to be quitted not being displayed when window previews were disabled.
Fix this by updating the "Quit" menu item and separators always, regardless of the show-window-preview setting.
Replaces #939
=> Update AppIconMenu when window-previews are disabled

docking.js
We were creating a barrier after each call to the updateBarrier
callback, regardless of the current dock state. If the dock is already shown,
this creat a barrier which is never removed, resulting in the mouse
being trapped. Check for the current dock state instead.
This is triggered for instance when an application enter/exit
fullscreen on any monitor.
The logic controlling pressure barriers and dock state needs
improvements but ths should fix it for now.
fix #743
=> Fix mouse trapped due to barrier set up with dock shown.

docking.js
This change has been part of commit 1334ab3 that was still based on a
version before of commit 4b5af3a and so it was using Utils.DisplayWrapper
which don't exist anymore now.
=> docking: Don't use non-existent Utils.DisplayWrapper.getWorkspaceManager()

docking.js
The dock is visible when xscreensaver is triggered. This occur in Gnome
Shell 3.34, but not in 3.30. Slighly changing the position of the dock
in the stack seems to fix the problem. This might be a consequence of
upstream commit 2bd80579eddba9804871ce6c8de742bdf9b1d800.  This also
requires to disable the machinery in place to keep the dock on top of
everying on screen grab seems. Luckily, this seems to not to be
necessary anymore.
Fix #1002
=> Fix bug with xscreensaver.

appIcons.js
Gnome Shell 3.36 changed the API to open the settings. From 3.36.2 on
it also provides a convenience function to make that easier - use it
if available.
See also https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1163
Complementary to https://github.com/micheleg/dash-to-dock/pull/1097
---
Note: I'm not very experienced in js, so any suggestions to make this more elegant are welcome :)
=> Use new convenience function to open settings

docking.js
Wait that the show animation is completed before we try to hide a sliding
dock.
This fixes a regression caused by commit 662604b because with clutter
animations, a transition would remove the previous one queued for an object,
and thus the delay wouldn't work anymore.
So, instead of relying on the waiting time, let's just use the _animateIn()
onComplete() callback in order to request an hide while the show animation
is still going.
=> docking: Delay hide requests if we're currently showing

docking.js
Introduced in 4a40b1de64ba83656f0df40cc8c91eb34cd4d302. The problem was
occurring only when monitor.y !=0 (and with extended mode with execute
the code).
=> Fix regression (wrong sign when computing position).

stylesheet.css
This is to make the showapps button cover the screen corner where the
mouse is likely to land when trying to activate it.
This slightly modifies the rendering of the dash (removing some
padding), restoring the look and behaviour of previous gnome-shell
releases.
Fix #1167.
=> Remove padding the dock ends in panel mode.

locations.js
Drive icons could potentially have an emblem applied to them, meaning
that we need to be aware of the emblemed icon type and how to resolve
an icon for us to use.
Fixes #1175.
=> locations: Handle emblemed mount icons

dash.js
This pull request fixes the JS error reported in here https://github.com/micheleg/dash-to-dock/issues/1188
The approach is quite simple, if there is no "first icon", it means there's no icons at all and there's nothing to to anymore, so simply return. I hope the approach is fine, I tested it on my installation and it fixes the problem reported in the issue.
Fixes #1188
=> Fix JS error when the dash has no icons

appIcons.js
Fixes #1224.
All translatable strings are now correctly exported by gettext, however I did not test running the actualy extension after this change and I don't fully understand the gettext domain/shell domain thing. But hopefully, it should work fine.
=> appIcons: Fix translatable strings

schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml
Fixes 'appplication' typo on dash-to-dock description for some options.
=> Fixes typo on org.gnome.shell.extensions.dash-to-dock

appIconIndicators.js, appIcons.js, dash.js, dbusmenuUtils.js, docking.js, launcherAPI.js, utils.js
This adds support for the two properties of a libunity LauncherEntry object not yet supported: "quicklist" and "urgent". Quicklist entries are added to the right-click menu of the launcher as dynamic menu items. The urgent flag, if set, gives the icon a short dancing animation to call attention to it. These features don't seem to be widely used by applications, but there's a bit of a chicken-and-egg problem here; why would application authors spend time writing code to use them if they aren't supported by the desktop?
I encountered some trouble with the libunity communication, and I also had some trouble understanding the intent of the original libunity integrating code, so I took the liberty of refactoring it into a pattern that, among other advantages, is more robust to multiple DBus …
=> Support more Unity features (quicklist, urgent properties)

COPYING
Downloaded from:
https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
This fixes the address, which was causing RPM lint error:
incorrect-fsf-address
=> Update to latest wording of the GPLv2 license

dash.js, docking.js, metadata.json
Add support to GNOME 3.38, ensuring that we keep compatibility with 3.36 (at least a cycle it looks like we can do it easily).
Added few different versioned codepaths and few cleanups.
=> Add support to GNOME 3.38

windowPreview.js
All window previews now at least resemble the shape of the source window instead of defaulting to max values which made them either stretched or squished.
=> windowPreviews now scale properly

fileManager1API.js
On my system I have two drives mounted under `/mnt/Data` and `/mnt/Data 2`.
I noticed that browsing to the latter drive in Nautilus would also produce an open indicator in the dock for the former drive.
This simple tweak fixes the problem and should prevent issues of a similar nature from occurring.
=> Fix getWindows for a location in the dock

Settings.ui, appIcons.js, schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml
This action mixes the behaviour of 'Focus or show previews' and
'Minimize or show previews', ie. it acts as follows:
- if app is not running, create new window
- if app is running but not focused, focus (first) window
- if app is running and focused:
- if app has multiple windows, show previews
- otherwise, minimize window
=> appIcons: Add 'Focus, minimize or show previews'

Settings.ui, prefs.js, schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml, utils.js, windowPreview.js
This adds a new option to the configuration interface to manipulate the preview size scale:
* scale from 0,00 to 1,00 in steps of 0,05
* default is 0,00 a.k.a. "auto" which is the current scale calculation
I've implemented this since the current scale calculation results in a scale of 0,1429 for my monitor which is waaaaay too small IMHO. I prefer having a scale of 0,40.
=> Add new setting: preview size scale

docking.js
Make it compatible with the [Vertical Overview](https://extensions.gnome.org/extension/4144/vertical-overview/) extension, scrolling on the dock will move to the correct workspace in both horizontal and vertical layouts.
Update the code in https://github.com/micheleg/dash-to-dock/pull/1402#issuecomment-853986202 to make it work in both cases.
=> Make dash-to-dock work with both horizontal and vertical workspaces

docking.js, extension.js
We don't need it when the GNOME dash is being replaced.
([LP: #1940925](https://bugs.launchpad.net/bugs/1940925))
**Requires:** https://salsa.debian.org/gnome-team/gnome-shell/-/merge_requests/52 so this really is intended for ubuntu-dock only.
CC @3v1n0
=> Disable starting in the overview

Makefile, Settings.ui, _stylesheet.scss, appIconIndicators.js, appIcons.js, dash.js, docking.js, fileManager1API.js, locations.js, prefs.js, schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml, theming.js, utils.js, windowPreview.js
~~This only achieves "bare minimum" functionality.~~
~~Settings aren't all tested (the Unity style stuff is probably broken, for example), the settings UI needs fixing, and it is _very much_ WIP.~~
~~The most basic functionality is usable though - and I'll be adding to this branch (though other contributors' work is welcome)~~
We're approaching _initial_ release quality :partying_face: 
Known issues:
(will update as issues get fixed or found)
Known trade-offs:
=> Port to GNOME 40.

docking.js
Since extensions get disabled on screen lock and then restarted on
screen unlock, we don't want that to get animated again. Particularly
if you have a maximized window during that time, it looks ugly and
stuttery animating a full workarea relayout.
Fixes: https://launchpad.net/bugs/1947149
=> docking: Only animate on shell startup, not every extension startup

docking.js
This has been an issue with dash-to-panel for quite some time now:
https://github.com/home-sweet-gnome/dash-to-panel/issues/1265#issuecomment-882035294
https://github.com/home-sweet-gnome/dash-to-panel/issues/1500
Whenever you would start nautilus you would see:
```
TypeError: dockManager is null getRunningApps@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:653:9
wrapWindowsManagerApp/fileManagerApp._updateWindows@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:258:9
wrapWindowsManagerApp/windowsChangedId<@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/locations.js:250:24
```
However this file belongs to dash-to-dock and not dash-to-panel.
So I did some digging. Turns out that the changes introduced in …
=> Cleanup nautilus listeners

Settings.ui, appIconIndicators.js, prefs.js, schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml
@micheleg Just a small PR on something I tried. I turned off the glossy effect and IMO it looks cleaner, especially if only a few apps are open.
I added an option for this. Here are a few screenshots:
**Before:**
**After:**
=> Unity7 backlight: optional glossy effect

fileManager1API.js, locations.js
Leave the garbage collector do its job, especially on locations where
the object may be shared by multiple instances and its lifecycle can't
be controlled here.
See: https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2020#note_1302901
=> locations: Do not manually dispose objects

po/ru.po
There wasn't `#, javascript-format` before `msgid "Quit %d Windows"`. So in Russian Ubuntu it has been for several years that if you open two or more instances of one application and right-click on it, there will be the one English line.
=> Update Russian localization

appIcons.js
Hide windows that hint not to be shown in the task bar.
Fix for #1629
=> Fix window counter (exclude hidden windows)

docking.js, prefs.js, schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml
As described in #1598 i experienced issues when displaying the dock on a secondary monitor and unplugging or replugging another secondary monitor. This behavior was caused because the monitor to display the dock on is stored as an index in `preferred-monitor` and the index of that monitor changed. However, when studying the source code, i realized that this behavior needs to be retained for backwards compatibility purposes.
This pull request fixes the issue while retaining backwards compatibility: 
- There is a new setting called `preferred-monitor-by-connector`. It stores the monitor to display the dock on using the port it is connected to instead of its index.
- The setting `preferred-monitor-by-connector` is only used when `preferred-monitor` is set to `-2`. (a previously unused value, …
=> add preferred-monitor-by-connector as an alternative to storing the index

Settings.ui, intellihide.js, prefs.js, schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml
Does as indicated in the title, useful for smaller screens where you want dash availability without giving up all of the vertical space.
=> Adds an intellihide mode for always-on-top (on non-fullscreen windows)

Makefile, desktopIconsIntegration.js, docking.js
When Dash to Dock is in autohide mode, Desktop Icons NG (DING) can't know how much space the dock need, so icons can be put below the dock and become inaccessible.
This is a generic fix for this. It adds a class (DingIntegration) that allows other extensions to communicate with Ding and any other extension that would need to know variable margins to avoid to put elements there.
The other part is at https://gitlab.com/rastersoft/desktop-icons-ng/-/merge_requests/196
=> Desktop icons integration

README.md
A small change made simply for convience. This pull request makes it so that the build procress is a bit simpler and faster to do by adding the cd so you don't have to do it manually.
=> Add the cd step so that make doesn't show errors

Settings.ui, appIcons.js, dash.js, docking.js, fileManager1API.js, locations.js, metadata.json, prefs.js, schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml, utils.js
Refactor locations handling to have a more native Shell integration.
A part the various improvements and features, the main trigger for this was (as per the main commit message):
```
As per gjs 1.72 it won't be possible to inject an interface vfunc as it
used to work in previous versions, this would make gnome-shell to crash
as we may try to get the location "apps" ID which is now null (and not
customId anymore).
So, let's re-implement the things in a cleaner way by actually using
real custom AppInfo's that are still based on Gio.DesktopAppInfo
(beause the shell will still need to be such type), but that are
implementing the needed virtual functions of the parent interface.
As per this, we can finally use native shell mount operations to handle
mount options such as mounting encrypted …
```
=> Locations refactory to use native Gio.AppIcon's (for GNOME 42 support)

appIcons.js, dash.js, docking.js
Fixes #1714, #1755 and https://launchpad.net/bugs/1967121
Also fixed in ubuntu-dock via #1739
=> [dash-to-dock] Don't autohide while a menu is open

theming.js
This patch adds compatibility with Desktop Icons NG for Dynamic Transparency functionality by taking into account that, under Wayland, the "skip-taskbar" property can be set only under very specific circumstances (that, currently, only DING does fulfill).
You can read about issue details at https://gitlab.com/rastersoft/desktop-icons-ng/-/issues/230
=> Add compatibility with DING for Dynamic Transparency

docking.js
Since Gnome42 has deprecated panel corners, for optimum backwards compatibility the method `_adjustPanelCorners` and `_revertPanelCorners` should first check if the `PanelCorner` has the left and right corner, and only then check for its value.
Source for Gnome42 port documentation: https://gjs.guide/extensions/upgrading/gnome-shell-42.html#panel-corner
=> Ensure that PanelCorner has given properties before checking the value

Settings.ui, dash.js, docking.js, prefs.js, schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml
This is to fix the issue: Prevent dock from popping out when gnome is in do-not-disturb   #1634 
The users will be able to choose in the intelligent hide settings whether they want the dock to be shown for urgent notifications or not.
=> Added option to turn on/off show dock for urgent notifications

metadata.json
Works without a hitch (functionality wise, afaict) in GNOME 43.alpha.
Using [FCGU](https://gitlab.com/fabiscafe/gnome-unstable) repo and [AUR](https://wiki.archlinux.org/title/Arch_User_Repository) package [gnome-shell-extension-dash-to-dock43](https://aur.archlinux.org/packages/gnome-shell-extension-dash-to-dock43) to test.
There's a JS error reported in the logs, however, this doesn't seem to hinder functionality.
```shell
jul 14 17:58:19 x11sslf gnome-shell[256233]: JS ERROR: Exception in callback for signal: open-state-changed: TypeError: this.setForcedHighlight is not a function
_onMenuPoppedDown@resource:///org/gnome/shell/ui/appDisplay.js:3209:14
_onMenuPoppedDown@/usr/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIcons.js:1292:56 …
```
=> metadata: Add support for gnome-shell 43

docking.js
Object.hasOwn isn't supported by mozjs 91
=> docking: Check for corners availability using standard checks

dash.js, locations.js, prefs.js, utils.js
Some random fixes for 42, addressing various comments of the [extension review](https://extensions.gnome.org/review/32340).
=> 42 cleanups

Makefile, Settings.ui, appIcons.js, appSpread.js, docking.js, schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml
or "Application Spread" as it was called back with Unity7.
https://user-images.githubusercontent.com/4941802/172016701-2032f8a2-2ebb-4f8e-b955-8347873a3661.mp4
---
This is a manual rebase of #519, which is by now almost exactly 3 years old. I also slightly reduced changes to `appIcons.js`. I hope it is enough for @micheleg to review this..
=> implement "minimize or overview" with only current app windows

appIcons.js
Fixes error:
```
(gnome-shell:147771): Gjs-WARNING **: 03:30:11.038: JS ERROR: Exception in callback for signal: open-state-changed: TypeError: this.setForcedHighlight is not a function
_onMenuPoppedDown@/data/GNOME/gnome-shell/js/ui/appDisplay.js:3135:14
_onMenuPoppedDown@/data/GNOME/JHBUILD_HOME/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIcons.js:1339:56
popupMenu/<@/data/GNOME/JHBUILD_HOME/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIcons.js:1358:26
_emit@resource:///org/gnome/gjs/modules/core/_signals.js:114:47
close@/data/GNOME/gnome-shell/js/ui/popupMenu.js:944:14
itemActivated@/data/GNOME/gnome-shell/js/ui/popupMenu.js:606:28
_connectItemSignals/<@/data/GNOME/gnome-shell/js/ui/popupMenu.js:643:22 …
```
=> appIcons: Implement setForcedHighlight function in DockShowAppsIcons

docking.js
We used to pass the wrong state argument to maybeAdjustBoxToDock that may have lead to some unwanted behavior.
=> docking: Fix arguments for overridden _getAppDisplayBoxForState

locations.js
This is consistent with what happens with other applications.
LP: #1971012
=> locations: Make FileManagerApp emit windows-changed on workspace swithes

docking.js
Coming from https://extensions.gnome.org/review/34780
=> docking: Remove pending show-overlay timeouts on destruction

docking.js
This can happen in a VM where the hypervisor changes the Xorg display resolution at startup, during the login animation.
Fixes: https://launchpad.net/bugs/1989170, https://launchpad.net/bugs/1989726
=> docking: Handle when dash is destroyed during the login animation

docking.js, utils.js
If docks gets destroyed early during startup animation (as it may happen
when there are resolution or other monitor changes), we need to
completely finish the animation, but we can safely perform a new one in
these cases, as this happens early enough.
Closes: #1770
LP: #1965208
=> docking: Ensure we perform the startup animation completely on docks updates

windowPreview.js
When using global scaling the size of the previews is not properly adjusted to match user settings, and we end up having too small previews for the selected resolution.
=> windowPreviews: Take global scaling in account to set the clone sizes

intellihide.js
Currently the dock hides when the desktop window from the DING extension is shown, and the dock is in case IntellihideMode.ALL_WINDOWS:
This proposed fix, excludes the DING extension windows specifically, both the Gtk3 and Gtk4 versions from handled windows, so uses resource usage and takes it out of consideration for any case statement when considering hiding the dock.
This is more specific than #1879 and works in all cases. Also works in conjunction with #1888 which is needed to fix transparency.
=> Don't detect and track DING windows for intellihide

intellihide.js
This builds on #1890 
Currently _handledWindow is called twice for every window on the list when considering for intellihide.
This makes the call only once.
=> Optimize intellihide for handled windows

_stylesheet.scss, appIcons.js, windowPreview.js
Various cleanups and improvements to the window previews, and finally fixing a very-old bug that was causing the previews not to be properly aligned.
=> Windows previews improvements

Settings.ui, appIcons.js, docking.js, prefs.js, schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml
Resolves https://github.com/micheleg/dash-to-dock/issues/1859.
The distracting dance/shake animation for urgent application icons has always really annoyed me. I finally thought I'd do something about it and contribute a setting for whether dancing should be enabled; and being mostly a copy-paste job, was easier than I expected.
Tested using gnuplot, which when not minimised and not the foreground application, makes its icon urgent upon `reread`:
```bash
echo 'plot sin(x); pause 1; reread' > x && gnuplot x; rm x
```
Edit: I wasn't sure what to do about translations. Is there something automated? Should we be using Google Translate?
=> Make urgent application icon dance toggleable

theming.js
In Gtk4-DING, the Gtk4 port of the desktop icons extension, the desktop X11 window cannot be detected by "DESKTOP" type. It is handled by the same code as wayland windows, and needs to be detected by the skip_taskbar hint. This enables correct transparency of the dock when on X11 with Gtk4-DING.
This, works with #1879, which is needed for fixing intellihide of Dock with Gtk4-DING.
=> Fix Transparency for Gtk4 DING

appIcons.js
This may be supported when using remote launcher actions
=> appIcons: Allow marking urgent applications when not running

appIconIndicators.js
These information are only available when a widget is on the stage.
Avoids errors such as:
```
(gnome-shell:1188360): St-CRITICAL **: 16:17:59.545: st_widget_get_theme_node called on the widget [0x55e8f933c050 StDrawingArea.progress-bar:insensitive] which is not in the stage.
== Stack trace for context 0x55e8f6e9cc50 ==
#0   7ffedefee410 b   /data/GNOME/JHBUILD_HOME/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIconIndicators.js:783 (b2170e811f0 @ 222)
#1   7ffedefeeb20 b   /data/GNOME/JHBUILD_HOME/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIconIndicators.js:886 (b2170e81380 @ 86)
#2   7ffedefeebf0 b   /data/GNOME/JHBUILD_HOME/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/appIconIndicators.js:700 (b2170e81060 @ 75)
#3 …
```
=> appIconIndicators: Do not load theme node for off-stage widgets

appIconIndicators.js
=> appIconIndicators: Unpack texture names, not the iconInfo

locations.js
Even though that's only used in a delayed promise, it's still better to go in order.
=> locations: Create launchMaxWait in order

windowPreview.js
Dispose the window previews close button left or right depending on the button layout settings.
Closes: #1918
=> windowPreview: Honor button layout settings for the window preview close

Settings.ui, appIcons.js, prefs.js, schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml
Hide application tooltip option
=> Hide tooltip

prefs.js
Instead of enforcing a minimum window height of 850. The height is now resizable.
Fixes: https://github.com/micheleg/dash-to-dock/issues/1975
=> prefs: Set default window height to 850, if it fits

Settings.ui, po/ar.po, po/cs.po, po/de.po, po/el.po, po/es.po, po/eu.po, po/fr.po, po/gl.po, po/hu.po, po/id.po, po/it.po, po/ja.po, po/nb.po, po/nl.po, po/pl.po, po/pt.po, po/pt_BR.po, po/ru.po, po/sk.po, po/sr.po, po/sr@latin.po, po/sv.po, po/tr.po, po/uk_UA.po, po/zh_CN.po, po/zh_TW.po, prefs.js
Convention for this extensions seems to be that titles don't have full stops, but descriptions do. This PR just fixes the 9 cases I found that break that convention.
=> Fix consistency of full stops in strings

Settings.ui, appIconIndicators.js, appIcons.js, docking.js, notificationsMonitor.js, prefs.js, schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml
It's now possible to:
- Toggle the emblems at all
- Disable the notification counters
- Control whether the notification numbers are summed with the applications-provided counts (no by default)
Closes: #1964
=> Add more options to control the emblems visibility

Makefile, locations.js, locationsWorker.js
Getting the default location handler has to be a sync operation because
the shell uses a sync operations to launch applications.
However, this may have lead to hanging the shell, making it unresponsive.
We handled this within the shell itself, but to get it working we had to
keep keep the main loop busy, leading to other issues (see LP: #2013070)
As per this, use an external helper that queries the files paths so that
we don't have to make the shell main loop to iterate, but all this is done
in an external process that we call still synchronously but with a minimal
timeout so that the main session won't ever hang.
Improves fix for: #1949
LP: #2013070
=> locations: Use an external helper to get the location handler

docking.js
Especially under X11 we may get "monitors-changed" event while the startup animation is in progress, while some of them were addressed by [!2269 (merged)](https://github.com/GNOME/gnome-shell/-/merge_requests/2269), we still have an issue happening:
GNOME shell is preparing the animation and awaiting for bg changes
Monitors are changed, during this phase we destroy the current background managers
=> The "loaded" signals we were waiting for, won't ever happen
This implies that we are stuck in `await this._updateBackgrounds()`; and thus we keep staying in broken mode.
Ubuntu issue is https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/+bug/2019751 it can be simulated with https://gitlab.gnome.org/3v1n0/gnome-shell/-/snippets/5749
Similar to …
=> Fix Startup infinite await

Settings.ui, dash.js, docking.js, notificationsMonitor.js, prefs.js, schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml
Added two options:
- Keep icons always centered when in panel mode (under Position and Size)
- Show _Show Apps_ button in the edge when using Panel mode (under Launchers)
This allows getting these results (same when show-apps is shown at the beginning):
Closing: #1746
=> Support centered icons in panel mode

intellihide.js
This is a workaround for issue #2013. As far as I could tell this works in most cases of popup menus (by right clicks) in GNOME wayland session. The only exception I meet is the multilevel popup menu from Telegram (illustrated in #2013), but with showing urgent notifications off it also works without problems.
`Meta.WindowType.POPUP_MENU` is not added to this list as I find that it has side effects for Qt xwayland programs: on my machine the intellihide is triggered every time I right-clicked in Okular (xwayland). However I could not reproduce this within my GNOME OS VM so it might be caused by other factors.
=> intellihide: add dropdown menu to handled window types

docking.js
Avoid using internal functions, since we have public LayoutManager methods we can use instead.
=> docking: Use upstream addChrome to track actors

docking.js
We were allocating the ControlsManagerLayout using the whole work area geometry but then in the auto-hide mode we were reducing the size of the available area again, creating problems when the available space was reduced. Leading to non-clickable or activatable search results.
To prevent this, perform layout allocation using the available space even when the dock is in autohide mode.
Closes: #1612
LP: #1979096
=> docking: Do ControlsManagerLayout allocation with box-adjusted workArea

dash.js
When using a floating show apps icon setup, it needs to be at the same level of the dash box, but we can't use the same container because upstream code only uses that for application icons, and this assumption may break things such as DnD and potentially other things.
So move things in a new container.
Closes: #2010
=> dash: Use a different container to hold floating ShowAppsIcon

dash.js
dash: Take in account the number of removed favorites to add the separator
When a favorite is removed the separator should be shifted accordingly,
so use the old separator position as reference
=> Removed favorites fix

docking.js
We need to ensure that input region is affected by the dock even when it's not in auto-hide mode. In fact before we were not applying this to the dock actor, but still to the scroll one.
Now we're doing it for the whole group.
Closes: #2032, #2024
=> docking: Always affect the input region when adding the dock

docking.js
If the overview was closed by clicking on the dash, and the cursor left the dash before the animation finished, the dock would still be visible after it should also be hidden.
Updating the dock visibility ensures the visibility isn't impacted by ignored signals during the animation.
I couldn't see any open issues for this, and since it was a simple fix I just made a PR instead of an issue. If I've missed the open issues, I can add them to the commit message if required :)
=> docking: Update dock visibility after overview hide animation is done

appIconIndicators.js
This is the same attempt to fix https://github.com/micheleg/dash-to-dock/issues/1493, in which we separate `Gio.ThemedIcon` from `Gio.LoadableIcon` but now with the `const` keyword and using list unpacking, as is done in similar pieces around the file.
I apologise for closing the previous merge request, GitHub asked to remove my previous commit when I clicked to sync my branch.
I read the documentation on how to cache and async it, but I couldn't make sense of the documentation, sorry.
When `iconTexture` is a `Gio.ThemedIcon`, it seems we can use [choose_icon](https://lazka.github.io/pgi-docs/Gtk-3.0/classes/IconTheme.html#Gtk.IconTheme.choose_icon) or [lookup_icon](https://lazka.github.io/pgi-docs/Gtk-3.0/classes/IconTheme.html#Gtk.IconTheme.lookup_icon), and the former is better suited …
=> Fix missing dominant color

.eslintrc.yml, Makefile, appIconIndicators.js, appIcons.js, appSpread.js, dash.js, dbusmenuUtils.js, dependencies/gi.js, dependencies/shell/extensions/extension.js, dependencies/shell/misc.js, dependencies/shell/ui.js, desktopIconsIntegration.js, docking.js, extension.js, fileManager1API.js, imports.js, intellihide.js, launcherAPI.js, lint/eslintrc-gjs.yml, lint/eslintrc-shell.yml, locations.js, locationsWorker.js, metadata.json, notificationsMonitor.js, prefs.js, theming.js, utils.js, windowPreview.js
Use ESM imports as gnome-45 requires, so drop compatibility with all the
old versions so that we could modernize things a bit in future.
Closes: #2066
=> GNOME 45 support - ESM porting

metadata.json
86 is skipped because e.g.o 500 error tricked me and rejected that.
=> Releasing v87

appIcons.js, dependencies/gi.js
Meta.Rectangle has been deprecated, fixes logs being flooded with:
`Meta.Rectangle is deprecated, use Mtk.Rectangle instead`
=> appIcons: Use Mtk.Rectangle instead of Meta.Rectangle

Makefile
Some strings are not generated due to redundant option "-k" (leftover from commit 51db80abc3ec5c6c0621a0ba74f04919cb3f0b12)
In result most translations lack:
msgid "Show Details"
msgid "Launch using Integrated Graphics Card"
msgid "Launch using Discrete Graphics Card"
msgid "Failed to launch “%s”"
=> Fix dashtodock.pot generation (avoid missing strings for translations)

appIcons.js
=> appIcons: Add support for translating plural forms

po/pl.po
My understanding is that "Empty" here is a verb in imperative, not an adjective. The previous translation was correct only if "Empty" was as adjective.
=> Fix Polish translation of "Empty Trash"

appIcons.js
Close #2104
`Show Details` menu label uses the default translation of the Gnome Shell. But the text of the Gnome Shell menu item is `App Details`, therefore this label is always displayed in English.
With the old label:
With the new label it's correct displays Gnome Shell localized string:
=> Change "Show Details" to GNOME's "App Details"

dash.js
When a new application is opened, the background usually results in being blurry, unless the mouse cursor hovers over the dash, just like in the following screenshots:
Such a problem was already well documented in the issue #1722.
This pull request fixes this issue by overriding the show() method from DashItemContainer in DockDashItemContainer and simulating a hover over the item once the animation is finished.
=> Fix for blurry background when opening a new application

_stylesheet.scss, appIconIndicators.js, appIcons.js, dash.js, docking.js, metadata.json, theming.js, utils.js, windowPreview.js
add_actor() has been removed after being deprecated, and it must be replaced with add_child(). Also, there are two add methods that also have to be changed.
Tested in Gnome 46 alpha, in a Fedora RawHide system. I also tested it in Gnome 45, but doesn't work, so it must be only 46.
=> Update for Gnome Shell 46

desktopIconsIntegration.js
Dockmanager can be null, and this spams the log if desktopIconsIntegration class is initialized and used.
desktopIconsIntegration class is initialized and called from the extension and really should not have any other dependencies other than the shell, it is meant to be used and can be used as is by any extension if called as is independently without modifications.
Fix resource path for Extension
=> Remove any dependency on dockmanager in desktopIconsIntegration.js

_stylesheet.scss, appIconIndicators.js
As commented in https://github.com/ubuntu/yaru/issues/4016, the progress bar, with its 3D gradient track, doesn't fit very well in the current Gnome/Yaru theme.
This patch changes this, allowing to set all the colors in the bars using CSS: the background color and outline width and color both for the track and the progress bar itself, and also use either plain colors or gradients in each of the four elements, allowing to also specify the start and stop points.
=> Fix progress bar colors

docking.js
1. Make `STARTUP_ANIMATION_TIME` non-zero again.
2. Stop trying to fully replace the startup animation when we can just use the existing one upstream gnome-shell provides.
3. Slide the dock in when upstream's startup animation is done.
Closes: #2110 and https://bugs.launchpad.net/bugs/2058468
=> Fix startup animation

docking.js
When overview shows, this._animateIn is called in
_onOverviewShowing(). And when overview hides, _updateDashVisibility() might call this._animateIn() again, which makes the unredirection always disabled and brings performance issue in some cases.
This commit replaces the counter for unredirection by a boolean value, to make logic more clear, and disabling/enabling unredirection balanced.
---
Fixes #2192.
=> intellihide: Fix unexpected unredirection disable with overview

docking.js
As requested by the g.e.o review, it's not really a big deal though since this signal is going to really last few frames and the extension is not really unloaded by that time.
/cc @vanvugt
=> docking: Use the signal handler to disconnect on startup-completed signal

locations.js
In case we're unmounting a volume we were optionally removing its icon
but this was also leading cancelling the operation that in the Gio queue
caused the action not to be fully performed.
So once, we've removed a volume or umounted a mount, we don't really
care about cancelling the ongoing operations since they should be done
already.
[LP: #1993054](https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/+bug/1993054)
=> locations: Do not cancel operations after a volume has been umounted / removed

dash.js, utils.js, windowPreview.js
When setting the middle button click as "show window preview", the previews aren't shown. Instead, an empty rectangle appears and a lot of errors are shown in the log.
This patch fixes this.
Fix #2202
=> Fix window preview in Gnome 45

locations.js
This sadly requires parsing the error strings since there are not good APIs yet, but that's how upstream handles this too, so let's accept it for now.
See: https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3300
=> locations: Ask again for password on encryption failures

desktopIconsIntegration.js
This patch is the same patch from master, but for merging in "ubuntu-dock"
The extension state naming has changed from gnome shell 45 to gnome shell 46, so the code to notify margins to DING wasn't being able to detect when an extension was active, and so it didn't prevent to put icons below the dock.
This patch fixes it.
=> Fix communication with DING (same patch for "ubuntu-dock" branch)

desktopIconsIntegration.js
The extension state naming has changed from gnome shell 45 to gnome shell 46, so the code to notify margins to DING wasn't being able to detect when an extension was active, and so it didn't prevent to put icons below the dock.
This patch fixes it.
=> Fix communication with DING

docking.js, notificationsMonitor.js
Since the destroy() function can be called several times, it is paramount to don't call objects that have been freed in previous calls.
=> Don't show error messages when disabling

appIconIndicators.js, appIcons.js, launcherAPI.js
For the new RAA we need to be able to mark an icon as "disabled" while it is being updated. The current Unity LauncherAPI (https://wiki.ubuntu.com/Unity/LauncherAPI) doesn't support this, so this patch adds an extra option for this.
https://docs.google.com/document/d/1--DgBRl6AqNiyjW_luOjl1dDzsIZPlF0Ukc7INW9_XQ
=> UDENG-3111: allow to disable an icon in the dock during updates

docking.js
Since `this._container` no longer exists (gnome-shell@b58119d5c6?) in GNOME 47, allocating the entire overview would fail and the shell was non-functional.
Fixes:
```
Gjs-CRITICAL **: 17:10:01.720: JS ERROR: TypeError: actor is undefined
findIndexForActor@resource:///org/gnome/shell/ui/layout.js:992:22
findMonitorForActor@resource:///org/gnome/shell/ui/layout.js:999:26
_prepareMainDash/<@file:///home/dan/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:2233:52
@resource:///org/gnome/shell/ui/init.js:21:20
```
=> docking: Fix allocation failure in GNOME 47 that completely broke the shell

windowPreview.js
This is a fix for an issue where activating a window from the window preview list would not reliably give focus to that window (#1972)
I don't know why reordering these two lines of code fixes it, but there's [confirmation](https://github.com/micheleg/dash-to-dock/issues/1972#issuecomment-2200097373) from another user that the change also works for them.
=> Fix window selected from preview not getting focus

metadata.json
Closes: https://github.com/micheleg/dash-to-dock/issues/2246
=> metadata.json: Enable support for gnome-shell 47

Makefile, _stylesheet.scss, appIconIndicators.js, appIcons.js, appIconsDecorator.js, dependencies/shell/ui.js, docking.js, imports.js, launcherAPI.js, notificationsMonitor.js, po/de.po, po/ko.po, utils.js
Shows Unity Icons indicators everywhere (overview, search results...) when they are enabled.
Handles updating applications better when in they're not pinned to the dock.
=> Icon indicators everywhere

docking.js, prefs.js, schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml
The "Show Applications" button fails because the Overview.ANIMATION_TIME property is now read-only (it has a "const" prefix), so it's not possible to overwrite it to show the applications list "instantaneously". It "does nothing" and shows this error in the log:
```
ago 28 12:20:46 raster3-PROX14-AMD gnome-shell[534248]: JS ERROR: TypeError: "ANIMATION_TIME" is read-only
_onShowAppsButtonToggled/<@file:///home/raster/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/docking.js:2491:21
@resource:///org/gnome/shell/ui/init.js:21:20
```
This patch removes the option of disabling the animation, thus fixing the problem.
=> Remove Animate Show Applications from the desktop (Fix "Show Applications" button)

Settings.ui, appIconIndicators.js, schemas/org.gnome.shell.extensions.dash-to-dock.gschema.xml
It is known that in GNOME 46.2 the default indicator has undergone breaking changes, and now its positioning is faulty: #2222. So I decided it would be nice to make a custom indicator like `Dots`, but with just one dot and as close in size and style as possible to the default indicator.
P.S: It doesn't replace the default indicator for backwards compatibility reasons, but it does provide an alternative in newer versions of GNOME. In the future, this could be made the default, instead of the current `Dots` option.
=> Add `Dot` running indicator style

_stylesheet.scss, appIconIndicators.js, appIcons.js, appIconsDecorator.js, utils.js
Move progress bar on icon baseline on overview and permit tuning their positioning and size better via style variables.
This is following the upstream theme, while for yaru some further customization will be done
=> Progress bar theming tuning

appIcons.js, appIconsDecorator.js
If an application is a snap package, and the snap store is installed we can show the snap packages details as we do for other non-snap applications if GNOME Software is installed
UDENG-4316
UDENG-4700
=> appIcons: Show app details menu for snap applications

appIconIndicators.js, theming.js
Similar to #2285 to handle more cases of #2284.
/cc @vanvugt
=> Use Cogl.Color when defined everywhere

appIconIndicators.js, theming.js
While now there's only Cogl.Color, in previous versions we had both so giving Cogl priority broke the theming support
Closes: #2307
=> theming: Give Clutter.Color priority over Cogl.Color

appIconsDecorator.js, utils.js
By adding parameters in commit 611690cc33 we ended up hiding the base object constructor parameter, and so the support for automatic disconnection on parent object destruction.
Fixes: #2297
=> utils: Use an extra parameter for property injector constructor

_stylesheet.scss
This patch fixes the dot in Default mode when not enabling "Few customizations".
Tested in Ubuntu Noble, Fedora 46 (100% and 200% scale), and Ubuntu Oracular (both in Ubuntu Desktop and Classic Gnome sessions).
Fix: #2222
=> Fix dot position on Gnome 46.2 and greater

appIcons.js
With the single underscore (_) we can re-use original translation.   
However, for the 'Pin to Dock' there's no match since GNOME 42-47 original label is 'Pin to Dash'.   
Using two underscores (__) as a translation function resolves #2330
=> Make the 'Pin to Dock' label translatable

docking.js, metadata.json
Closes: https://github.com/micheleg/dash-to-dock/issues/2347
=> Add GNOME 48 support

docking.js
Issue: When starting a drag event while the dock is overlapping (e.g., when a window is maximized) and intelligent autohide is enabled, the dock fails to hide after the drag event ends.
This pull request invokes `_updateDashVisibility` after the drag event concludes to ensure the dock's state is correctly updated.
Fix: #2174
=> Fix autohide after drag event

appIcons.js
So for the dash-to-dock menu item use a popup separator as well with the dash to dock name and a settings menu item.
=> appIcons: Be consistent on menu items styles

po/de.po
Fixes a funny translation.
- Schwellwert = value that relates to a swelling
- Schwellenwert = value that relates to a threshold
- [Duden: Schwellenwert](https://www.duden.de/suchen/dudenonline/Schwellenwert)
- [LEO: Schwellenwert](https://dict.leo.org/german-english/Schwellenwert)
- [LEO: Threshold](https://dict.leo.org/german-english/Threshold)
- [LEO: Schwellung](https://dict.leo.org/german-english/Schwellung)
=> Correct German translation of threshold

docking.js
In pull request #2331 you fixed the 'Pin to Dock' translation in [appIcons.js](https://github.com/micheleg/dash-to-dock/blob/master/appIcons.js) but you forgot that the same translation is used also in [docking.js](https://github.com/micheleg/dash-to-dock/blob/master/docking.js).
I changed the `_` shell translation function to the `__` extension function and added the needed imports.
Now in the GNOME list of applications, the correct translation for 'Pin to Dock' is picked up for the languages that provide it. Previously it was working only in the Dock context menu.
=> Fixing 'Pin to Dock' translation in GNOME list of applications menu

Settings.ui
- Updated `upper` to `100`
- Updated `step-increment` to `5`
- Updated `page-increment` to `25`
Fixes #2420
=> Settings UI Update for Pressure Threshold Adjustment Fields
